name: Simple Declarative

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hello-world:
    name: Hello and World
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello"

      - name: World
        run: echo "World"
